services:
  - type: web
    name: zapanon-web-master
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.0.0